### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by PuneetKohli** [evmavrop/Hyperion#1]
Looking to run this on a custom video of my own. Any pointers appreciated

**Comment by evmavrop** [comment]
I included a Doxygen documentation in a commit a made this morning (index.html). I hope it helps you.

Now regarding the video input mode:
a) overload the InputParameters::Configure method and change the first parameter to a container of your frames or a "pointer" to them. 
b) create a member function in InputParameters class so you can read your input. Call the method in the overloaded InputParameters::Configure. You can save your frames in Mat containers so it will be easier to turn them into my Image containers.
c) call dehazeProc every time you want to apply the algorithm on a frame of your video. 

I hope I helped. Tell me if you want and more informations.

**Comment by PuneetKohli** [comment]
Thanks for the documentation. Do you think it would be possible to extend the code to accept either an image or a video as a command line parameter and run as a black box?

**Comment by evmavrop** [comment]
I implemented the video input option. Just edit the hyperion.cfg file. Use full paths for the input and output files. Set input file type to 1.
